### ISSUE TITLE
RMF_structuredInit is missing

### ISSUE THREAD

**Issue by stati64** [conor42/fast-lzma2#2]
RMF_structuredInit in FL2_compressCurBlock()
RMF_structuredBuildTable in FL2_compressCurBlock()
RMF_structuredIntegrityCheck in  RMF_integrityCheck()
RMF_structuredGetMatch in RMF_getMatch()

**Comment by conor42** [comment]
Which build did this occur in? These functions are supplied by compiling radix_struct.c
