### ISSUE TITLE
7-Zip ZS addin

### ISSUE THREAD

**Issue by mcmilk** [conor42/fast-lzma2#4]
Hello,

I just started to do some work on 7-Zip ZS again... how could this "faster" lzma put together within 7-Zip without too much hassle ?

Your code is currently out of the master branch, but there is an extra branch called radyx ;-)

Greetings, Tino

**Comment by conor42** [comment]
Hi Tino,

I'm releasing a technothriller novel this week or next, but after that I'll have time to add the codec to 7-Zip ZS. Recent versions of 7-Zip allow multiple implementations of the same codec, so it will integrate more easily than before :)

**Comment by mcmilk** [comment]
Cool, and easy going ... the zstd code needs also to be modified... I will do this in december I think.
