### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by jinfeihan57** [conor42/fast-lzma2#6]

**Comment by jinfeihan57** [comment]
@conor42 
I also added the flzma2 algorithm to the [p7zip](https://github.com/szcnick/p7zip). Can you add a description of the [p7zip ](https://github.com/szcnick/p7zip)project to readme? 
Or  I can provide a PR about it.
Thank you!

**Comment by conor42** [comment]
Nice 👍
Added a link.
